version: '3.4'

services:
  db:
    container_name: trio-db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trio
    ports:
      - 6500:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
  esdata: {}
